version: '3'

services:
  mysqldb:
    # image: mysql:5.7
    command: --innodb-use-native-aio=0
    build:
      context: mysql
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - fullcyclenetwork

  node:
    build:
      context: node
    container_name: nodeapp
    networks:
      - fullcyclenetwork
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"

  nginx:
    build:
      context: nginx
    container_name: nginx
    networks:
      - fullcyclenetwork
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - "node"

networks:
  fullcyclenetwork:
    driver: bridge